apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: infra
spec:
  selector:
    app: prowlarr
  ports:
  - name: http
    port: 9696
    protocol: TCP
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 192.168.1.207