apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/npiv/proxymoxy.git'
    path: pihole
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
