apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config-pvc
  namespace: infra
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi