apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: infra
spec:
  selector:
    app: homer
  ports:
  - name: homer-web
    port: 8080
    protocol: TCP
    targetPort: homer-web
  type: LoadBalancer
  loadBalancerIP: 192.168.1.209