apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: infra
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: '2.1.1'
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 1m
  values:
    persistentVolume:
      enabled: true
      size: 8Gi
    serviceTCP:
      type: LoadBalancer
    serviceUDP:
      type: LoadBalancer
    adminPassword: "changeme"
    adlists:
      - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
      - "https://mirror1.malwaredomains.com/files/justdomains"
      - "http://sysctl.org/cameleon/hosts"
      - "https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt"
      - "https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt"
      - "https://hosts-file.net/ad_servers.txt"

---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mojo2600
  namespace: flux-system
spec:
  interval: 10m
  url: https://mojo2600.github.io/pihole-kubernetes/
