apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
        - name: TZ
          value: "America/New_York"
        - name: WEBPASSWORD
          value: "admin123"  # Change this password
        - name: PIHOLE_DNS_
          value: "8.8.8.8;8.8.4.4"
        - name: VIRTUAL_HOST
          value: "pihole.homelab.local"
        - name: PROXY_LOCATION
          value: "pihole"
        - name: FTLCONF_LOCAL_IPV4
          value: "192.168.1.0/24"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq
          mountPath: /etc/dnsmasq.d
        - name: custom-dns
          mountPath: /etc/pihole/custom.list
          subPath: custom.list
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      volumes:
      - name: etc-pihole
        persistentVolumeClaim:
          claimName: pihole-etc
      - name: etc-dnsmasq
        persistentVolumeClaim:
          claimName: pihole-dnsmasq
      - name: custom-dns
        configMap:
          name: pihole-custom-dns