apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: infra
spec:
  selector:
    app: jellyfin
  ports:
  - name: jellyfin-web
    port: 8096
    protocol: TCP
    targetPort: jellyfin-web
  type: LoadBalancer
  loadBalancerIP: 192.168.1.204