apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: infra
spec:
  selector:
    app: radarr
  ports:
  - name: http
    port: 7878
    protocol: TCP
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 192.168.1.205