apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: infra
spec:
  selector:
    app: sonarr
  ports:
  - name: http
    port: 8989
    protocol: TCP
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 192.168.1.204