apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config-pvc
  namespace: infra
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nzbget-downloads-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.100
    path: /mnt/hdd-data/nzbgetdownloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-downloads-pvc
  namespace: infra
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: nzbget-downloads-pv