apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config-pvc
  namespace: infra
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-media-pvc
  namespace: infra
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: plex-media-pv