apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: lscr.io/linuxserver/nzbget:latest
        ports:
        - containerPort: 6789
          name: nzbget-web
          protocol: TCP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Brussels"
        volumeMounts:
        - name: nzbget-config
          mountPath: /config
        - name: nzbget-media
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: nzbget-config
        persistentVolumeClaim:
          claimName: nzbget-config-pvc
      - name: nzbget-media
        persistentVolumeClaim:
          claimName: nzbget-media-pvc