apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: infra
spec:
  selector:
    app: nzbget
  ports:
  - name: nzbget-web
    port: 6789
    protocol: TCP
    targetPort: nzbget-web
  type: LoadBalancer
  loadBalancerIP: 192.168.1.208