apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: infra
spec:
  selector:
    app: pihole
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: infra
spec:
  selector:
    app: pihole
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  type: LoadBalancer
