apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: infra
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      initContainers:
      - name: password-reset
        image: busybox:1.35
        command: ['sh', '-c', 'rm -f /etc/pihole/setupVars.conf']
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
          subPath: pihole
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 67
          name: dhcp
          protocol: UDP
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: TZ
        - name: WEBPASSWORD
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: WEBPASSWORD
        - name: DNS1
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DNS1
        - name: DNS2
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DNS2
        - name: DNSMASQ_LISTENING
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DNSMASQ_LISTENING
        - name: PIHOLE_DNS_
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: PIHOLE_DNS_
        - name: DNSSEC
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DNSSEC
        - name: CONDITIONAL_FORWARDING
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: CONDITIONAL_FORWARDING
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
          subPath: pihole
        - name: pihole-data
          mountPath: /etc/dnsmasq.d
          subPath: dnsmasq.d
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        livenessProbe:
          httpGet:
            path: /admin
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: pihole-pvc
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 127.0.0.1
        - 1.1.1.1