apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  namespace: documents
spec:
  type: ClusterIP
  selector:
    app: paperless-ngx
  ports:
  - name: http
    port: 8000
    targetPort: 8000