apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/npiv/proxymoxy.git  # Update with your repo
    targetRevision: HEAD
    path: k8s-manifests/applications
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true