apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  labels:
    app.kubernetes.io/name: storage
spec:
  project: default
  source:
    repoURL: https://github.com/npiv/proxymoxy.git
    targetRevision: HEAD
    path: k8s/infra/storage
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3