apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Brussels"
        volumeMounts:
        - name: homeassistant-config
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          privileged: true
      volumes:
      - name: homeassistant-config
        persistentVolumeClaim:
          claimName: homeassistant-config-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime