apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: infra
spec:
  selector:
    app: homeassistant
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 192.168.1.211